In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from matplotlib import dates as mpl_dates

In [2]:
btcDataset = pd.read_csv('../Data/BTC-BRL/2019.csv')
btcDatasetSample = pd.read_csv('../Data/BTC-BRL/dez2019.csv')

In [3]:
btcDataset.drop(btcDataset.columns[[0,5,6]], axis=1, inplace=True)

In [4]:
btcDataset.head()

close      open       max       min
0  29.201,1  29.699,9  29.999,8  29.057,0
1  29.699,9  29.820,0  30.200,0  29.400,0
2  29.820,0  29.775,0  30.210,0  29.560,5
3  29.775,0  29.560,0  29.889,0  29.560,0
4  29.560,0  29.600,0  29.894,4  29.033,0

In [5]:
btcDataset['close'] = btcDataset['close'].str.replace(',', '').astype(float)
btcDataset['open'] = btcDataset['open'].str.replace(',', '').astype(float)
btcDataset['max'] = btcDataset['max'].str.replace(',', '').astype(float)
btcDataset['min'] = btcDataset['min'].str.replace(',', '').astype(float)

In [6]:
btcDataset.head()

close     open      max      min
0  29.2011  29.6999  29.9998  29.0570
1  29.6999  29.8200  30.2000  29.4000
2  29.8200  29.7750  30.2100  29.5605
3  29.7750  29.5600  29.8890  29.5600
4  29.5600  29.6000  29.8944  29.0330

In [7]:
X = btcDataset.iloc[:, 1:].values
y = btcDataset.iloc[:, 0].values

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
for i in range(3):
    X[:,i] = le.fit_transform(X[:,i])

In [9]:
print(y)

[131 139 141 140 135 136 138 142 147 156 133 137 130 145 127 128 132 134
 149 143 144 148 155 165 168 167 166 160 161 170 176 185 195 175 188 158
 157 139 172 162 189 209 218 225 241 242 240 251 253 255 248 265 256 259
 269 273 266 263 254 260 257 262 246 264 249 245 237 209 153 152 196 210
 202 197 194 207 203 211 217 221 222 215 233 230 199 204 180 198 203 212
 228 229 219 208 224 227 214 238 267 289 302 305 313 311 306 307 315 309
 310 314 311 294 303 319 322 324 325 332 330 331 318 285 283 281 282 290
 317 321 299 298 312 288 295 335 337 301 292 308 302 300 333 341 344 342
 349 350 350 340 343 297 291 286 278 272 250 243 244 252 268 270 261 271
 274 277 278 275 276 258 232 304 284 336 339 328 348 351 346 334 327 320
 323 338 296 293 326 345 352 329 353 347 316 287 280 279 247 236 231 239
 213 205 200 181 178 163 169 151 171 173 154 164 146 192 220 216 223 206
 226 235 234 201 187 184 179 174 191 190 186 150 159 183 193 182 177 126
 129 125 124 123 122 120 119 121 118 115 110 108 10

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [11]:
print(y_test)

[315  99 242 166 217  36 228  71 120 138 318 341  95  76  68 146  56 305
 184 333 344 205 260  59  38 107 153   5 319 287 282 313 128 139 269 136
 257 295  90 249 171  48 220  93 144  50 216 223 119 245 328 187 125 278
 219 273 256 301 212 203  11  91 142 302   4  22 266 283 201 270 194 284
 322  58 264 121  39  19 108   6 148 349 350 255  51  17  45 169  92  74
  65 155]


In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [13]:
y_pred = classifier.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0.0